language: java
sudo: false
script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)

jdk: openjdk8
cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.m2"
install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=false -Dmaven.javadoc.skip=true -B -V
notifications:
  email: false