sudo: required
services:
  - docker

before_install:
  - printenv
  - docker build -t kaktas/service_test -f ./Dockerfile.dev . --build-arg GITHUB_USERNAME=$GITHUB_USERNAME --build-arg GITHUB_TOKEN=$GITHUB_TOKEN

after_success:
  - bash <(curl -s https://codecov.io/bash)

jdk: openjdk8
cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.m2"
install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=false -Dmaven.javadoc.skip=true -B -V
notifications:
  email: false